#!/usr/bin/env bash
#fjdfkdjfdkj
for i in {1..100};do
echo "$i"
if (( "$i" % 3 == 0 && "$i" % 5 == 0 ));then
	echo "FizzBuzz"
if (( "$i" % 3 == 0 ));then;
echo "Fizz"
elif (( "$i" % 5 == 0 ));then
echo "Buzz" 
fi
done
