#!/usr/bin/env bash
#ffdfd
for file in *; do
       if [ -e "$file" ]; then
           if [[ "$file" == *-* ]]; then
            echo "${file#*-}"
        else
    
            echo "$file"
        fi
    fi
done

