#!/usr/bin/env bash
#nsfkfkalffk
if [ -e "school" ]; then
  echo "school file exists"
else
  echo "school file does not exist"
fi

if [ -e "school" ] && [ -z "school" ]; then
  echo "school file is empty"
elif [ -e "school"] && [ -n "school" ]; then
  echo "school file is not empty"
fi

if [ -f "school" ]; then
  echo "school is a regular file"
fi
