#!/usr/bin/env bash
#nsfkfkalffk
if [ -e "School" ]; then
  echo "school file exists"
else
  echo "school file does not exist"
fi

if [ -e "School" ] && [ ! -s "School" ]; then
  echo "school file exists but is empty"
elif [ -s "School" ]; then
  echo "school file is not empty"
fi

if [ -f "School" ]; then
  echo "school is a regular file"
fi
rm school

