#!/usr/bin/env bash
# shellcheck disable=SC2009

pids=$(ps -ef | grep "4-to_infinity_and_beyond" | grep -v grep | awk '{print $2}')
if [ -n "$pids" ]; then
  for pid in $pids; do
    python3 -c "import os, signal; os.kill($pid, signal.SIGTERM)"
  done
fi
